name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  tags:
    - 'v*'  # 当推送 v 开头的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hfspacedeploy:latest
    
    - name: Save Docker image
      run: docker save hfspacedeploy:latest | gzip > hfspacedeploy.tar.gz
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hfspacedeploy
        path: hfspacedeploy.tar.gz
        compression-level: 0
    
    # 🆕 仅在推送标签时创建 Release
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: hfspacedeploy.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
